name       : xdg-utils
version    : 1.1.2
release    : 5
source     :
    - https://portland.freedesktop.org/download/xdg-utils-1.1.2.tar.gz : 951952e2c6bb21214e0bb54e0dffa057d30f5563300225c24c16fba846258bcc
license    : MIT
component  : desktop.core
summary    : Tools to assist with desktop integration tasks
description: |
    xdg-utils is a a set of command line tools that assist applications with a variety of desktop integration tasks. It is required for Linux Standards Base (LSB) conformance.
builddeps  :
    - docbook-xml
    - links
    - xmlto
rundeps    :
    - perl-net-dbus
    - perl-x11-protocol
    - xset
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
