name       : xdg-utils
version    : 1.1.3
release    : 8
source     :
    - https://portland.freedesktop.org/download/xdg-utils-1.1.3.tar.gz : d798b08af8a8e2063ddde6c9fa3398ca81484f27dec642c5627ffcaa0d4051d9
license    : MIT
component  : desktop.core
summary    : Tools to assist with desktop integration tasks
description: |
    xdg-utils is a a set of command line tools that assist applications with a variety of desktop integration tasks. It is required for Linux Standards Base (LSB) conformance.
builddeps  :
    - docbook-xml
    - lynx
    - xmlto
rundeps    :
    - perl-net-dbus
    - perl-x11-protocol
    - xset
setup      : |
    %patch -p1 < $pkgfiles/xdg-open.patch
    %patch -p1 < $pkgfiles/xdg-settings.patch
    %configure
build      : |
    %make
install    : |
    %make_install
