name        : xdg-utils
version     : 1.1.1
release     : 3
source      :
    - http://portland.freedesktop.org/download/xdg-utils-1.1.1.tar.gz : b0dd63a2576e0bb16f1aa78d6ddf7d6784784a098d4df17161cd6a17c7bc4125
license     :
    - GPL-2.0
summary     : Tools to assist with desktop integration tasks
builddeps   :
    - xmlto
    - docbook-xml
    - links
description : |
    xdg-utils is a a set of command line tools that assist applications with a variety of desktop integration tasks. It is required for Linux Standards Base (LSB) conformance.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
